<a href="https://colab.research.google.com/github/harshm413/numpy-basics/blob/main/NumpyBasics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import numpy as np

In [3]:
arr=np.array([[[1, 2, 3, 4],
                           [5, 6, 7, 8],
                           [9, 10, 11, 12]],

                          [[13, 14, 15, 16],
                           [17, 18, 19, 20],
                           [21, 22, 23, 24]]])

In [4]:
arr.T

array([[[ 1, 13],
        [ 5, 17],
        [ 9, 21]],

       [[ 2, 14],
        [ 6, 18],
        [10, 22]],

       [[ 3, 15],
        [ 7, 19],
        [11, 23]],

       [[ 4, 16],
        [ 8, 20],
        [12, 24]]])

In [6]:
arr.dtype

dtype('int64')

In [7]:
arr.size

24

In [8]:
arr.ndim

3

In [9]:
arr.itemsize

8

In [10]:
arr.nbytes

192

In [11]:
arr.shape

(2, 3, 4)

In [13]:
arr.all()

True

In [14]:
arr.any()

True

In [16]:
arr.argmax()
#index

23

In [17]:
arr.max()
#value

24

In [18]:
arr.max(0)

array([[13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [23]:
arr.astype(np.int32).copy()

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int32)

In [20]:
arr

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [21]:
arr.dtype

dtype('int64')

In [22]:
arr.copy()

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [24]:
arr.mean()

12.5

In [25]:
arr.mean(0)

array([[ 7.,  8.,  9., 10.],
       [11., 12., 13., 14.],
       [15., 16., 17., 18.]])

In [26]:
arr.ndim

3

In [27]:
arr.reshape((4,2,3))

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24]]])

In [28]:
arr

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [34]:
arr2=np.array([[[8, 4, 2, 6],
                               [5, 1, 7, 3],
                               [9, 10, 11, 12]],

                              [[16, 12, 14, 10],
                               [17, 18, 19, 20],
                               [21, 22, 23, 24]]])

In [44]:
arr2.sort()

In [45]:
arr2

array([[[ 2,  4,  6,  8],
        [ 1,  3,  5,  7],
        [ 9, 10, 11, 12]],

       [[10, 12, 14, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [39]:
arr3=np.array([[[1.2, 2.5, 3.0, 4.7],
                            [5.3, 6.1, 7.8, 8.2],
                            [9.6, 10.0, 11.4, 12.9]],

                           [[13.7, 14.2, 15.8, 16.4],
                            [17.1, 18.5, 19.0, 20.3],
                            [21.6, 22.2, 23.9, 24.7]]])

In [40]:
arr3.round(3)

array([[[ 1.2,  2.5,  3. ,  4.7],
        [ 5.3,  6.1,  7.8,  8.2],
        [ 9.6, 10. , 11.4, 12.9]],

       [[13.7, 14.2, 15.8, 16.4],
        [17.1, 18.5, 19. , 20.3],
        [21.6, 22.2, 23.9, 24.7]]])

In [41]:
arr3.dtype

dtype('float64')

In [46]:
arr.std()

6.922186552431729

In [47]:
arr.std(1)

array([[3.26598632, 3.26598632, 3.26598632, 3.26598632],
       [3.26598632, 3.26598632, 3.26598632, 3.26598632]])

In [49]:
arr3.std(1).round(1)

array([[3.4, 3.1, 3.4, 3.4],
       [3.2, 3.3, 3.3, 3.4]])

In [50]:
arr3.sum(2)

array([[11.4, 27.4, 43.9],
       [60.1, 74.9, 92.4]])

In [51]:
arr3.tolist()

[[[1.2, 2.5, 3.0, 4.7], [5.3, 6.1, 7.8, 8.2], [9.6, 10.0, 11.4, 12.9]],
 [[13.7, 14.2, 15.8, 16.4],
  [17.1, 18.5, 19.0, 20.3],
  [21.6, 22.2, 23.9, 24.7]]]

In [53]:
arr3.var()

48.76331597222222

In [57]:
arr2.view(np.int32)

array([[[ 2,  0,  4,  0,  6,  0,  8,  0],
        [ 1,  0,  3,  0,  5,  0,  7,  0],
        [ 9,  0, 10,  0, 11,  0, 12,  0]],

       [[10,  0, 12,  0, 14,  0, 16,  0],
        [17,  0, 18,  0, 19,  0, 20,  0],
        [21,  0, 22,  0, 23,  0, 24,  0]]], dtype=int32)

Data types in numpy are as :
**np.int8, np.int16, np.int32, np.int64**,
**np.float16, np.float32, np.float64**

##**Done**